Resources:
  WebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      # Using a very unique name to avoid any S3 conflicts
      BucketName: !Sub 'vivian-dev-site-${AWS::AccountId}-${AWS::Region}'
      WebsiteConfiguration:
        IndexDocument: index.html

  MyTestParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: '/myapp/config/test-mode'
      Type: 'String'
      Value: 'enabled'

Outputs:
  BucketName:
    Value: !Ref WebsiteBucket
  BucketArn:
    Description: "The ARN of the S3 Bucket"
    Value: !GetAtt WebsiteBucket.Arn